lsi: false
safe: true
source: [https://catrinanowakowski.github.io]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
#theme: jekyll-theme-minimal


#social-network-links:
#  email: "someone@example.com"
#  rss: true  # remove this line if you don't want to show an RSS link at the bottom
#  github: catrinanowakowski
 


#  share-links-active:
#  github: true
#  email: true
